In [ ]:
import pandas as pd

In [2]:
data_path = "../splits/lunch_dinner/data_filtered_manually_1.csv"
data = pd.read_csv(data_path)
data.shape

(505, 34)

In [3]:
data.columns

Index(['sub', 'Carb', 'Protein', 'Fat', 'Fiber', 'Image path', 'Meal Type',
       'Amount Consumed', 'Timestamp', 'AUC', 'Calories', 'iAUC',
       'Baseline_Libre', 'Age', 'Gender', 'BMI', 'A1c', 'HOMA', 'Insulin',
       'TG', 'Cholesterol', 'HDL', 'Non HDL', 'LDL', 'VLDL', 'CHO/HDL ratio',
       'Fasting BG', 'Correct Nutrition', 'full_image_path', 'PWrapped',
       'LogitWrapped', 'LogitVisible', 'GapWrappedMinusVisible', 'IsWrapped'],
      dtype='object')

In [4]:
all_data_lunch = data[data["Meal Type"] == "Lunch"]
all_data_dinner = data[data["Meal Type"] == "Dinner"]
all_data_lunch.shape, all_data_dinner.shape, all_data_lunch.shape[0] + all_data_dinner.shape[0]

((312, 34), (193, 34), 505)

In [6]:
data["Baseline_Libre"].describe()

count    505.000000
mean      90.322244
std       28.288826
min       40.000000
25%       74.000000
50%       86.000000
75%       99.400000
max      302.400000
Name: Baseline_Libre, dtype: float64

In [9]:
all_data_lunch.groupby("sub")["Baseline_Libre"].describe()

,count,mean,std,min,25%,50%,75%,max
sub,,,,,,,,
1,6.0,80.311111,5.560282,69.800000,79.716667,81.933333,83.650000,85.000000
2,8.0,55.241667,13.225417,40.000000,40.000000,59.866667,64.600000,72.600000
3,1.0,78.000000,NaN,78.000000,78.000000,78.000000,78.000000,78.000000
4,10.0,70.580000,5.116620,62.400000,68.066667,69.933333,73.800000,77.866667
5,8.0,86.325000,11.434475,72.533333,77.950000,82.900000,94.200000,106.200000
6,9.0,81.422222,8.568028,68.800000,74.266667,79.866667,89.000000,93.000000
7,6.0,57.233333,12.453273,40.000000,51.233333,56.133333,62.883333,76.400000
8,9.0,71.103704,11.517480,56.466667,61.666667,71.800000,76.000000,94.000000
9,10.0,74.140000,9.467733,57.000000,68.566667,73.766667,79.450000,89.066667
10,8.0,83.950000,19.859946,66.200000,70.016667,76.700000,90.250000,121.866667
11,8.0,95.991667,5.409860,89.666667,91.650000,95.266667,98.983333,104.000000
12,8.0,101.608333,13.647463,86.400000,90.200000,98.533333,114.966667,117.933333
13,9.0,101.111111,16.119795,83.533333,92.400000,93.666667,104.600000,133.333333
14,5.0,84.346667,5.957330,78.333333,80.200000,81.866667,89.533333,91.800000
15,7.0,57.209524,11.293815,40.000000,53.100000,55.466667,62.400000,74.000000
16,5.0,73.306667,6.308830,62.466667,73.200000,76.200000,76.666667,78.000000
17,9.0,73.711111,10.882861,53.933333,73.000000,76.533333,78.000000,87.333333
18,9.0,92.059259,19.546936,58.866667,90.000000,91.933333,94.800000,130.000000
19,9.0,74.266667,5.804692,65.000000,68.600000,75.466667,80.000000,81.000000
20,8.0,93.966667,5.117911,87.200000,90.783333,93.100000,96.633333,103.200000
21,10.0,84.553333,7.342422,66.400000,83.650000,86.300000,89.000000,91.666667
22,4.0,101.350000,8.816378,95.400000,96.400000,97.800000,102.750000,114.400000
23,8.0,88.533333,8.561412,77.600000,85.050000,86.433333,89.533333,106.000000
26,9.0,70.303704,11.729076,49.000000,67.200000,74.133333,76.400000,82.200000
27,10.0,68.513333,8.363120,55.000000,65.083333,69.700000,72.050000,81.600000
28,7.0,92.085714,20.449421,68.200000,82.333333,85.133333,101.366667,123.866667
29,8.0,92.358333,12.944469,66.066667,89.866667,94.033333,96.900000,111.666667
30,3.0,139.222222,35.826268,112.800000,118.833333,124.866667,152.433333,180.000000
31,7.0,73.771429,8.180723,58.066667,71.566667,73.600000,79.600000,82.400000
32,7.0,77.685714,21.959009,50.400000,65.900000,73.200000,87.500000,113.400000
33,7.0,108.914286,33.357341,55.000000,94.833333,106.333333,129.066667,153.266667
34,8.0,85.066667,8.116689,73.400000,79.050000,84.533333,89.883333,97.000000
35,7.0,187.533333,55.065321,133.666667,162.400000,169.200000,191.333333,302.400000
36,5.0,105.680000,21.647140,77.066667,89.000000,113.000000,123.466667,125.866667
38,10.0,83.526667,2.969217,79.733333,81.883333,83.100000,84.300000,90.200000
39,5.0,138.693333,28.006134,102.466667,116.266667,147.666667,161.600000,165.466667
41,5.0,114.413333,36.449002,80.066667,87.666667,97.000000,149.533333,157.800000
42,1.0,96.266667,NaN,96.266667,96.266667,96.266667,96.266667,96.266667
43,9.0,71.533333,4.864155,63.000000,70.000000,72.200000,74.000000,80.000000
44,5.0,86.213333,13.635525,70.000000,80.800000,83.200000,90.200000,106.866667
45,4.0,96.583333,24.880596,66.000000,88.600000,96.700000,104.683333,126.933333
46,4.0,140.033333,81.878220,88.333333,91.483333,105.266667,153.816667,261.266667
47,5.0,144.426667,17.076989,119.333333,139.600000,144.800000,153.000000,165.400000
48,5.0,71.080000,12.431001,56.533333,62.266667,70.800000,77.933333,87.866667
49,7.0,97.542857,18.991945,82.933333,84.300000,88.000000,105.166667,132.933333

In [10]:
all_data_dinner.groupby("sub")["Baseline_Libre"].describe()

,count,mean,std,min,25%,50%,75%,max
sub,,,,,,,,
1,7.0,81.933333,6.381106,76.533333,78.133333,79.733333,83.366667,94.266667
2,10.0,74.120000,9.751723,65.400000,68.450000,70.266667,76.400000,95.400000
3,8.0,97.325000,11.035782,85.733333,89.916667,93.400000,103.533333,114.000000
4,15.0,88.097778,10.416466,70.266667,85.266667,87.533333,91.666667,113.200000
5,10.0,96.760000,9.022835,81.533333,92.183333,94.900000,102.733333,110.800000
6,10.0,84.506667,13.692034,55.066667,80.116667,84.933333,92.700000,102.066667
7,1.0,43.000000,NaN,43.000000,43.000000,43.000000,43.000000,43.000000
8,8.0,78.091667,6.948330,67.533333,74.316667,79.500000,84.000000,84.800000
9,7.0,98.285714,12.605802,81.800000,90.033333,96.933333,107.000000,115.200000
10,3.0,103.777778,19.420188,88.000000,92.933333,97.866667,111.666667,125.466667
11,7.0,106.790476,11.870813,89.066667,99.700000,104.133333,116.266667,122.400000
12,6.0,100.822222,11.452135,92.666667,94.183333,96.833333,100.783333,123.200000
13,8.0,109.491667,7.250873,99.466667,106.166667,109.500000,113.266667,120.133333
14,6.0,96.177778,10.643614,85.000000,88.450000,93.800000,102.100000,112.933333
15,9.0,49.133333,11.124797,40.000000,40.000000,46.000000,53.666667,73.000000
17,6.0,78.800000,12.281296,65.866667,72.183333,75.400000,82.166667,100.600000
18,4.0,104.250000,7.320064,94.000000,101.500000,106.500000,109.250000,110.000000
19,3.0,103.600000,12.185784,96.266667,96.566667,96.866667,107.266667,117.666667
21,1.0,96.000000,NaN,96.000000,96.000000,96.000000,96.000000,96.000000
23,1.0,87.933333,NaN,87.933333,87.933333,87.933333,87.933333,87.933333
26,5.0,88.026667,15.799902,60.066667,91.733333,94.266667,96.066667,98.000000
27,7.0,70.323810,6.357664,61.400000,67.300000,70.400000,71.933333,82.000000
28,8.0,110.741667,11.946518,96.000000,103.350000,111.133333,113.050000,135.800000
29,9.0,97.733333,4.478839,91.200000,94.200000,99.400000,100.000000,105.600000
31,2.0,77.100000,4.101219,74.200000,75.650000,77.100000,78.550000,80.000000
34,6.0,82.622222,26.434545,40.000000,72.000000,84.000000,100.300000,114.000000
38,1.0,107.266667,NaN,107.266667,107.266667,107.266667,107.266667,107.266667
41,6.0,122.166667,20.644924,99.466667,108.350000,121.066667,127.433333,157.733333
43,11.0,90.903030,14.417624,72.000000,81.833333,87.333333,99.600000,118.000000
44,1.0,114.000000,NaN,114.000000,114.000000,114.000000,114.000000,114.000000
46,4.0,199.966667,24.123540,182.666667,184.816667,191.100000,206.250000,235.000000
47,3.0,154.644444,5.584237,150.933333,151.433333,151.933333,156.500000,161.066667

In [12]:
all_meals = pd.read_csv('../splits/all_meals.csv')
all_meals.shape

(1336, 28)

In [13]:
all_meals["Timestamp"] = pd.to_datetime(all_meals["Timestamp"])

df = all_meals.sort_values(["sub", "Timestamp"]).copy()

df["Timestamp_before"] = df.groupby("sub")["Timestamp"].shift(1)
df["Timestamp_after"] = df.groupby("sub")["Timestamp"].shift(-1)

df["Minutes_before"] = (
    (df["Timestamp"] - df["Timestamp_before"])
    .dt.total_seconds()
    .div(60)
)

df["Minutes_after"] = (
    (df["Timestamp_after"] - df["Timestamp"])
    .dt.total_seconds()
    .div(60)
)

In [17]:
df.head(40)

,sub,Carb,Protein,Fat,Fiber,Image path,Meal Type,Amount Consumed,Timestamp,AUC,...,Non HDL,LDL,VLDL,CHO/HDL ratio,Fasting BG,Correct Nutrition,Timestamp_before,Timestamp_after,Minutes_before,Minutes_after
0,1,340.0,352.0,487.8,24.0,photos/00000005-PHOTO-2020-5-1-14-23-0.jpg,lunch,100.0,2020-05-01 14:23:00,9856.0,...,142,130,13,2.9,91,True,NaT,2020-05-02 08:18:00,NaN,1075.0
1,1,264.0,88.0,94.5,0.0,photos/00000010-PHOTO-2020-5-2-8-18-0.jpg,breakfast,100.0,2020-05-02 08:18:00,11848.5,...,142,130,13,2.9,91,True,2020-05-01 14:23:00,2020-05-02 12:00:00,1075.0,222.0
2,1,356.0,68.0,378.0,6.0,photos/00000012-PHOTO-2020-5-2-12-0-0.jpg,lunch,100.0,2020-05-02 12:00:00,10747.5,...,142,130,13,2.9,91,True,2020-05-02 08:18:00,2020-05-02 19:52:00,222.0,472.0
3,1,128.0,16.0,198.0,8.0,photos/00000016-PHOTO-2020-5-2-19-52-0.jpg,dinner,100.0,2020-05-02 19:52:00,10883.0,...,142,130,13,2.9,91,True,2020-05-02 12:00:00,2020-05-03 00:03:00,472.0,251.0
4,1,116.0,8.0,36.0,0.0,photos/00000018-PHOTO-2020-5-3-0-3-0.jpg,snacks,100.0,2020-05-03 00:03:00,11964.0,...,142,130,13,2.9,91,True,2020-05-02 19:52:00,2020-05-03 09:07:00,251.0,544.0
5,1,264.0,264.0,94.5,0.0,photos/00000019-PHOTO-2020-5-3-9-7-0.jpg,breakfast,100.0,2020-05-03 09:07:00,10966.5,...,142,130,13,2.9,91,True,2020-05-03 00:03:00,2020-05-03 14:51:00,544.0,344.0
6,1,104.0,268.0,270.0,6.0,photos/00000021-PHOTO-2020-5-3-14-51-0.jpg,lunch,100.0,2020-05-03 14:51:00,10213.5,...,142,130,13,2.9,91,True,2020-05-03 09:07:00,2020-05-03 20:02:00,344.0,311.0
7,1,112.0,36.0,90.0,6.0,photos/00000023-PHOTO-2020-5-3-20-2-0.jpg,dinner,100.0,2020-05-03 20:02:00,10489.5,...,142,130,13,2.9,91,True,2020-05-03 14:51:00,2020-05-03 22:26:00,311.0,144.0
8,1,44.0,28.0,27.0,0.0,photos/00000028-PHOTO-2020-5-3-22-26-0.jpg,snacks,100.0,2020-05-03 22:26:00,12085.5,...,142,130,13,2.9,91,True,2020-05-03 20:02:00,2020-05-04 09:17:00,144.0,651.0
9,1,264.0,88.0,378.0,0.0,photos/00000030-PHOTO-2020-5-4-9-17-0.jpg,breakfast,100.0,2020-05-04 09:17:00,11132.5,...,142,130,13,2.9,91,True,2020-05-03 22:26:00,2020-05-04 12:59:00,651.0,222.0
10,1,376.0,48.0,117.0,6.0,photos/00000032-PHOTO-2020-5-4-12-59-0.jpg,lunch,100.0,2020-05-04 12:59:00,12331.5,...,142,130,13,2.9,91,True,2020-05-04 09:17:00,2020-05-04 19:42:00,222.0,403.0
11,1,4.0,52.0,153.0,0.0,photos/00000035-PHOTO-2020-5-4-19-42-0.jpg,dinner,100.0,2020-05-04 19:42:00,10132.5,...,142,130,13,2.9,91,True,2020-05-04 12:59:00,2020-05-05 09:22:00,403.0,820.0
12,1,292.0,264.0,378.0,14.0,photos/00000040-PHOTO-2020-5-5-9-22-0.jpg,breakfast,100.0,2020-05-05 09:22:00,11087.5,...,142,130,13,2.9,91,True,2020-05-04 19:42:00,2020-05-05 21:05:00,820.0,703.0
13,1,4.0,108.0,18.0,0.0,photos/00000044-PHOTO-2020-5-5-21-5-0.jpg,dinner,100.0,2020-05-05 21:05:00,10752.5,...,142,130,13,2.9,91,True,2020-05-05 09:22:00,2020-05-06 08:54:00,703.0,709.0
14,1,96.0,88.0,94.5,0.0,photos/00000047-PHOTO-2020-5-6-8-54-0.jpg,breakfast,100.0,2020-05-06 08:54:00,11077.5,...,142,130,13,2.9,91,True,2020-05-05 21:05:00,2020-05-06 12:25:00,709.0,211.0
15,1,372.0,336.0,396.0,6.0,photos/00000049-PHOTO-2020-5-6-12-25-0.jpg,lunch,100.0,2020-05-06 12:25:00,10982.5,...,142,130,13,2.9,91,True,2020-05-06 08:54:00,2020-05-06 19:56:00,211.0,451.0
16,1,168.0,28.0,45.0,0.0,photos/00000051-PHOTO-2020-5-6-19-56-0.jpg,dinner,100.0,2020-05-06 19:56:00,10110.5,...,142,130,13,2.9,91,True,2020-05-06 12:25:00,2020-05-07 10:07:00,451.0,851.0
17,1,264.0,88.0,94.5,0.0,photos/00000055-PHOTO-2020-5-7-10-7-0.jpg,breakfast,100.0,2020-05-07 10:07:00,12182.5,...,142,130,13,2.9,91,True,2020-05-06 19:56:00,2020-05-07 14:12:00,851.0,245.0
18,1,304.0,88.0,171.0,24.0,photos/00000057-PHOTO-2020-5-7-14-12-0.jpg,lunch,100.0,2020-05-07 14:12:00,11947.5,...,142,130,13,2.9,91,True,2020-05-07 10:07:00,2020-05-07 21:50:00,245.0,458.0
19,1,72.0,7.6,18.0,0.0,photos/00000061-PHOTO-2020-5-7-21-50-0.jpg,snacks,100.0,2020-05-07 21:50:00,12342.5,...,142,130,13,2.9,91,True,2020-05-07 14:12:00,2020-05-08 09:58:00,458.0,728.0
20,1,264.0,264.0,94.5,0.0,photos/00000063-PHOTO-2020-5-8-9-58-0.jpg,breakfast,100.0,2020-05-08 09:58:00,11275.0,...,142,130,13,2.9,91,True,2020-05-07 21:50:00,2020-05-08 13:26:00,728.0,208.0
21,1,160.0,304.0,153.0,24.0,photos/00000065-PHOTO-2020-5-8-13-26-0.jpg,lunch,100.0,2020-05-08 13:26:00,9280.0,...,142,130,13,2.9,91,True,2020-05-08 09:58:00,2020-05-08 20:16:00,208.0,410.0
22,1,128.0,64.0,189.0,0.0,photos/00000067-PHOTO-2020-5-8-20-16-0.jpg,dinner,100.0,2020-05-08 20:16:00,12709.0,...,142,130,13,2.9,91,True,2020-05-08 13:26:00,2020-05-08 20:22:00,410.0,6.0
23,1,48.0,10.8,72.0,0.0,photos/00000068-PHOTO-2020-5-8-20-22-0.jpg,dinner,100.0,2020-05-08 20:22:00,12868.0,...,142,130,13,2.9,91,True,2020-05-08 20:16:00,2020-05-09 09:35:00,6.0,793.0
24,1,264.0,88.0,378.0,0.0,photos/00000074-PHOTO-2020-5-9-9-35-0.jpg,breakfast,100.0,2020-05-09 09:35:00,11347.5,...,142,130,13,2.9,91,True,2020-05-08 20:22:00,2020-05-09 13:46:00,793.0,251.0
25,1,172.0,80.0,180.0,24.0,photos/00000077-PHOTO-2020-5-9-13-46-0.jpg,lunch,100.0,2020-05-09 13:46:00,10253.0,...,142,130,13,2.9,91,True,2020-05-09 09:35:00,2020-05-10 09:27:00,251.0,1181.0
26,1,96.0,88.0,94.5,0.0,photos/00000083-PHOTO-2020-5-10-9-27-0.jpg,breakfast,100.0,2020-05-10 09:27:00,10884.0,...,142,130,13,2.9,91,True,2020-05-09 13:46:00,2020-05-11 10:58:00,1181.0,1531.0
27,1,292.0,88.0,378.0,14.0,photos/00000091-PHOTO-2020-5-11-10-58-0.jpg,breakfast,100.0,2020-05-11 10:58:00,11324.0,...,142,130,13,2.9,91,True,2020-05-10 09:27:00,NaT,1531.0,NaN
28,2,264.0,88.0,94.5,0.0,photos/00000008-PHOTO-2019-11-16-10-3-0.jpg,breakfast,100.0,2019-11-16 10:03:00,11547.0,...,90,78,12,2.0,93,True,NaT,2019-11-16 13:27:00,NaN,204.0
29,2,368.0,68.0,378.0,20.0,photos/00000011-PHOTO-2019-11-16-13-27-0.jpg,lunch,100.0,2019-11-16 13:27:00,7747.5,...,90,78,12,2.0,93,True,2019-11-16 10:03:00,2019-11-16 17:14:00,204.0,227.0
30,2,188.0,84.0,288.0,8.0,photos/00000015-PHOTO-2019-11-16-17-14-0.jpg,dinner,100.0,2019-11-16 17:14:00,9623.5,...,90,78,12,2.0,93,True,2019-11-16 13:27:00,2019-11-16 19:18:00,227.0,124.0
31,2,104.0,16.0,63.0,0.0,photos/00000018-PHOTO-2019-11-16-19-18-0.jpg,snacks,100.0,2019-11-16 19:18:00,11493.0,...,90,78,12,2.0,93,True,2019-11-16 17:14:00,2019-11-17 10:33:00,124.0,915.0
32,2,264.0,264.0,94.5,0.0,photos/00000020-PHOTO-2019-11-17-10-33-0.jpg,breakfast,100.0,2019-11-17 10:33:00,12169.5,...,90,78,12,2.0,93,True,2019-11-16 19:18:00,2019-11-17 14:24:00,915.0,231.0
33,2,64.0,264.0,126.0,8.0,photos/00000022-PHOTO-2019-11-17-14-24-0.jpg,lunch,100.0,2019-11-17 14:24:00,8301.0,...,90,78,12,2.0,93,True,2019-11-17 10:33:00,2019-11-18 09:41:00,231.0,1157.0
34,2,264.0,88.0,378.0,0.0,photos/00000028-PHOTO-2019-11-18-9-41-0.jpg,breakfast,100.0,2019-11-18 09:41:00,9190.5,...,90,78,12,2.0,93,True,2019-11-17 14:24:00,2019-11-18 13:15:00,1157.0,214.0
35,2,376.0,48.0,117.0,10.0,photos/00000030-PHOTO-2019-11-18-13-15-0.jpg,lunch,100.0,2019-11-18 13:15:00,10045.5,...,90,78,12,2.0,93,True,2019-11-18 09:41:00,2019-11-18 18:03:00,214.0,288.0
36,2,84.0,88.0,117.0,8.0,photos/00000033-PHOTO-2019-11-18-18-3-0.jpg,dinner,100.0,2019-11-18 18:03:00,8464.5,...,90,78,12,2.0,93,False,2019-11-18 13:15:00,2019-11-19 09:28:00,288.0,925.0
37,2,292.0,264.0,378.0,14.0,photos/00000037-PHOTO-2019-11-19-9-28-0.jpg,breakfast,100.0,2019-11-19 09:28:00,11414.5,...,90,78,12,2.0,93,True,2019-11-18 18:03:00,2019-11-19 13:05:00,925.0,217.0
38,2,76.0,128.0,135.0,10.0,photos/00000039-PHOTO-2019-11-19-13-5-0.jpg,lunch,100.0,2019-11-19 13:05:00,7900.5,...,90,78,12,2.0,93,True,2019-11-19 09:28:00,2019-11-19 19:09:00,217.0,364.0
39,2,108.0,20.0,9.0,2.0,photos/00000041-PHOTO-2019-11-19-19-9-0.jpg,dinner,100.0,2019-11-19 19:09:00,14962.5,...,90,78,12,2.0,93,True,2019-11-19 13:05:00,2019-11-19 19:15:00,364.0,6.0

In [21]:
data["Timestamp"] = pd.to_datetime(data["Timestamp"])

cols_to_add = [
    "Timestamp",
    "Timestamp_before",
    "Timestamp_after",
    "Minutes_before",
    "Minutes_after"
]

data = data.merge(
    df[cols_to_add],
    on="Timestamp",
    how="left"
)

In [22]:
data.shape

(505, 38)

In [23]:
data["Minutes_before"].describe()

count     480.000000
mean      296.995833
std       181.606114
min         4.000000
25%       214.000000
50%       272.500000
75%       348.500000
max      1479.000000
Name: Minutes_before, dtype: float64

In [24]:
all_data_lunch = data[data["Meal Type"] == "Lunch"]
all_data_dinner = data[data["Meal Type"] == "Dinner"]

In [25]:
all_data_lunch["Minutes_before"].describe()

count     288.000000
mean      302.753472
std       190.660374
min        51.000000
25%       220.750000
50%       267.000000
75%       318.250000
max      1479.000000
Name: Minutes_before, dtype: float64

In [26]:
all_data_dinner["Minutes_before"].describe()

count    192.000000
mean     288.359375
std      167.223715
min        4.000000
25%      172.500000
50%      300.500000
75%      394.500000
max      846.000000
Name: Minutes_before, dtype: float64

In [27]:
all_data_lunch["Minutes_after"].describe()

count     307.000000
mean      486.462541
std       357.179384
min        14.000000
25%       265.500000
50%       345.000000
75%       454.000000
max      1706.000000
Name: Minutes_after, dtype: float64

In [28]:
all_data_dinner["Minutes_after"].describe()

count     189.000000
mean      584.756614
std       336.435167
min         4.000000
25%       229.000000
50%       738.000000
75%       832.000000
max      1430.000000
Name: Minutes_after, dtype: float64

In [40]:
all_data_lunch[all_data_lunch["Minutes_before"] <= 60]['sub'].count()

1

In [32]:
all_data_lunch[all_data_lunch["Minutes_after"] <= 120]['sub'].count()

1

In [43]:
all_data_dinner[all_data_dinner["Minutes_before"] <= 60]['sub'].count()

27

In [34]:
all_data_dinner[all_data_dinner["Minutes_after"] <= 120]['sub'].count()

30

In [38]:
all_data_dinner.shape[0] - 30 - 38

125

In [39]:
505 - 3 - 1 - 30 - 38

433

In [44]:
505 - 1 -1 - 27 - 30

446

In [54]:
data[data["Minutes_after"].isna()]

,sub,Carb,Protein,Fat,Fiber,Image path,Meal Type,Amount Consumed,Timestamp,AUC,...,full_image_path,PWrapped,LogitWrapped,LogitVisible,GapWrappedMinusVisible,IsWrapped,Timestamp_before,Timestamp_after,Minutes_before,Minutes_after
30,2,28.0,8.0,198.0,2.0,photos/00000087-PHOTO-2019-11-24-18-18-0.jpg,Dinner,100.0,2019-11-24 18:18:00,11241.0,...,..\..\CGMacros\CGMacros-002\photos/00000087-PH...,0.001305,39.550323,46.190567,-0.066402,False,2019-11-24 17:58:00,NaT,20.0,NaN
64,4,100.0,32.0,81.0,2.0,photos/00000125-PHOTO-2023-9-20-20-30-0.jpg,Dinner,100.0,2023-09-20 20:30:00,11197.5,...,..\..\CGMacros\CGMacros-004\photos/00000125-PH...,0.000341,41.434800,49.418896,-0.079841,False,2023-09-20 18:01:00,NaT,149.0,NaN
108,7,160.0,304.0,153.0,26.0,photos/00000048-PHOTO-2023-11-10-12-24-0.jpg,Lunch,100.0,2023-11-10 12:24:00,5864.5,...,..\..\CGMacros\CGMacros-007\photos/00000048-PH...,0.000031,46.762600,57.133870,-0.103713,False,2023-11-09 18:30:00,NaT,1074.0,NaN
142,9,532.0,128.0,603.0,16.0,photos/00000080-PHOTO-2020-9-24-19-29-0.jpg,Dinner,100.0,2020-09-24 19:29:00,14230.5,...,..\..\CGMacros\CGMacros-009\photos/00000080-PH...,0.000319,47.235188,55.285030,-0.080498,False,2020-09-24 12:29:00,NaT,420.0,NaN
334,27,276.0,156.0,342.0,6.0,photos/00000073-PHOTO-2024-6-19-18-45-0.jpg,Dinner,100.0,2024-06-19 18:45:00,10263.0,...,..\..\CGMacros\CGMacros-027\photos/00000073-PH...,0.018075,43.270966,47.265972,-0.039950,False,2024-06-19 13:40:00,NaT,305.0,NaN
378,31,376.0,176.0,180.0,8.0,photos/00000103-PHOTO-2022-7-8-11-54-0.jpg,Lunch,100.0,2022-07-08 11:54:00,13604.0,...,..\..\CGMacros\CGMacros-031\photos/00000103-PH...,0.999888,55.882465,46.789375,0.090931,False,2022-07-08 07:18:00,NaT,276.0,NaN
385,32,376.0,176.0,180.0,8.0,photos/00000039-PHOTO-2022-1-10-13-31-0.jpg,Lunch,100.0,2022-01-10 13:31:00,7432.0,...,..\..\CGMacros\CGMacros-032\photos/00000039-PH...,0.982230,55.280617,51.268320,0.040123,False,2022-01-10 05:10:00,NaT,501.0,NaN
413,35,376.0,176.0,180.0,8.0,photos/00000110-PHOTO-2024-12-21-12-58-0.jpg,Lunch,100.0,2024-12-21 12:58:00,36924.0,...,..\..\CGMacros\CGMacros-035\photos/00000110-PH...,0.997550,53.131180,47.122128,0.060091,False,2024-12-21 06:53:00,NaT,365.0,NaN
504,49,376.0,176.0,180.0,8.0,photos/00000098-PHOTO-2025-5-20-12-53-0.jpg,Lunch,100.0,2025-05-20 12:53:00,19815.0,...,..\..\CGMacros\CGMacros-049\photos/00000098-PH...,0.976299,56.068264,52.350025,0.037182,False,2025-05-20 07:06:00,NaT,347.0,NaN

     sub  Minutes_after
0      1         1075.0
1      1          472.0
2      1          251.0
3      1          311.0
4      1          144.0
..   ...            ...
500   49          425.0
501   49          442.0
502   49          401.0
503   49          404.0
504   49            NaN

[505 rows x 2 columns]

In [68]:
clean_data = data[
    ((data["Minutes_after"].isna()) | (data["Minutes_after"] >= 120)) &
    ((data["Minutes_before"].isna()) | (data["Minutes_before"] >= 30))
].copy()

In [69]:
clean_data.shape

(462, 38)

In [70]:
clean_data.to_csv('../splits/lunch_dinner/filter_before_30_after_120.csv', index=False)

In [63]:
clean_data_lunch = clean_data[clean_data["Meal Type"] == "Lunch"]
clean_data_lunch.shape

(308, 38)

In [64]:
clean_data_lunch.to_csv('../splits/lunch_filter_before_120_after_120.csv', index=False)

In [2]:
data = pd.read_csv('../splits/lunch_dinner/filter_before_60_after_120.csv')
data.columns

Index(['sub', 'Carb', 'Protein', 'Fat', 'Fiber', 'Image path', 'Meal Type',
       'Amount Consumed', 'Timestamp', 'AUC', 'Calories', 'iAUC',
       'Baseline_Libre', 'Age', 'Gender', 'BMI', 'A1c', 'HOMA', 'Insulin',
       'TG', 'Cholesterol', 'HDL', 'Non HDL', 'LDL', 'VLDL', 'CHO/HDL ratio',
       'Fasting BG', 'Correct Nutrition', 'full_image_path', 'PWrapped',
       'LogitWrapped', 'LogitVisible', 'GapWrappedMinusVisible', 'IsWrapped',
       'Timestamp_before', 'Timestamp_after', 'Minutes_before',
       'Minutes_after'],
      dtype='object')

In [3]:
CAP_MINUTES = 240

for col in ["Minutes_before", "Minutes_after"]:
    data[f"{col}_missing"] = data[col].isna().astype(int)

    data[f"{col}_capped"] = (
        data[col]
        .clip(upper=CAP_MINUTES)
        .fillna(CAP_MINUTES)
    )

In [4]:
data.head()

,sub,Carb,Protein,Fat,Fiber,Image path,Meal Type,Amount Consumed,Timestamp,AUC,...,GapWrappedMinusVisible,IsWrapped,Timestamp_before,Timestamp_after,Minutes_before,Minutes_after,Minutes_before_missing,Minutes_before_capped,Minutes_after_missing,Minutes_after_capped
0,1,340.0,352.0,487.8,24.0,photos/00000005-PHOTO-2020-5-1-14-23-0.jpg,Lunch,100.0,2020-05-01 14:23:00,9856.0,...,0.023312,False,NaN,2020-05-02 08:18:00,NaN,1075.0,1,240.0,0,240.0
1,1,356.0,68.0,378.0,6.0,photos/00000012-PHOTO-2020-5-2-12-0-0.jpg,Lunch,100.0,2020-05-02 12:00:00,10747.5,...,-0.077575,False,2020-05-02 08:18:00,2020-05-02 19:52:00,222.0,472.0,0,222.0,0,240.0
2,1,128.0,16.0,198.0,8.0,photos/00000016-PHOTO-2020-5-2-19-52-0.jpg,Dinner,100.0,2020-05-02 19:52:00,10883.0,...,-0.106220,False,2020-05-02 12:00:00,2020-05-03 00:03:00,472.0,251.0,0,240.0,0,240.0
3,1,104.0,268.0,270.0,6.0,photos/00000021-PHOTO-2020-5-3-14-51-0.jpg,Lunch,100.0,2020-05-03 14:51:00,10213.5,...,-0.139810,False,2020-05-03 09:07:00,2020-05-03 20:02:00,344.0,311.0,0,240.0,0,240.0
4,1,112.0,36.0,90.0,6.0,photos/00000023-PHOTO-2020-5-3-20-2-0.jpg,Dinner,100.0,2020-05-03 20:02:00,10489.5,...,-0.088890,False,2020-05-03 14:51:00,2020-05-03 22:26:00,311.0,144.0,0,240.0,0,144.0

In [5]:
data.to_csv('../splits/lunch_dinner/filter_before_60_after_120_capped.csv', index=False)